"""
safety_checker.py
SQL safety validation and sanitization.
"""

import re


def sanitize_sql(sql: str) -> str:
    """
    Clean SQL generated by LLM.
    Removes markdown code blocks and extra spaces.
    """
    if not sql:
        return ""

    sql = sql.strip()

    # Remove markdown code blocks
    sql = re.sub(r"^```sql\s*", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"^```", "", sql)
    sql = re.sub(r"```$", "", sql)

    return sql.strip()


def is_safe_sql(sql: str) -> tuple[bool, str]:
    """
    Allow only SELECT queries.
    Block dangerous operations.
    """

    if not sql:
        return False, "Empty SQL query"

    sql_upper = sql.upper().strip()

    blocked_keywords = [
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "TRUNCATE",
        "CREATE",
        "REPLACE",
        "MERGE",
        "EXEC",
        "EXECUTE",
        "GRANT",
        "REVOKE",
        "COMMIT",
        "ROLLBACK",
    ]

    for keyword in blocked_keywords:
        if re.search(rf"\b{keyword}\b", sql_upper):
            return False, f"Dangerous operation detected: {keyword}"

    if not sql_upper.startswith("SELECT"):
        return False, "Only SELECT statements are allowed"

    return True, "Query is safe"